# Puerto de la aplicación
quarkus.http.port=8089

# Configuración de Keycloak (ajusta los valores según tu entorno)
#keycloak.auth-server-url=http://localhost:8083/
#keycloak.realm=master
#keycloak.resource=admin-cli
#keycloak.credentials.secret=mWXwITkn11nGyhdD34JVUuDrSNMSu689
#keycloak.ssl-required=external
#keycloak.public-client=true
#keycloak.bearer-only=false
#keycloak.admin.username=admin
#keycloak.admin.password=admin

keycloak.auth-server-url=http://localhost:8083/
keycloak.realm=billpay_app
keycloak.resource=cli_billpay_app
keycloak.credentials.secret=YGMyRIRzM2qa4hYZFxVVqrSQzRWlrZuB
keycloak.ssl-required=external
keycloak.public-client=true
keycloak.bearer-only=false
keycloak.admin.username=kuroroluzbell
keycloak.admin.password=123456


# SmallRye OpenAPI
# OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.enable=true
quarkus.oidc.auth-server-url=http://localhost:8083/realms/billpay_app
quarkus.oidc.client-id=cli_billpay_app
quarkus.oidc.application-type=service
quarkus.oidc.credentials.secret=YGMyRIRzM2qa4hYZFxVVqrSQzRWlrZuB
quarkus.oidc.public-client=true
# Configuración de logs y otros ajustes recomendados
quarkus.log.console.level=INFO
