# Puerto de la aplicación
quarkus.http.port=8089

# --- Configuración administrativa para crear usuarios, roles, etc. ---
keycloak.auth-server-url=http://localhost:8083/
keycloak.realm=billpay_app
keycloak.resource=cli_billpay_app
keycloak.credentials.secret=YGMyRIRzM2qa4hYZFxVVqrSQzRWlrZuB
keycloak.ssl-required=external
keycloak.public-client=true
keycloak.bearer-only=false
keycloak.admin.username=kuroroluzbell
keycloak.admin.password=123456

# --- Configuración OIDC para proteger endpoints y validar tokens ---
quarkus.oidc.auth-server-url=http://localhost:8083/realms/billpay_app
quarkus.oidc.client-id=cli_billpay_app
quarkus.oidc.credentials.secret=YGMyRIRzM2qa4hYZFxVVqrSQzRWlrZuB
quarkus.oidc.tls.verification=none
# quarkus.oidc.token.issuer=keycloak  # Comentado para evitar conflicto con el issuer del token
quarkus.oidc.application-type=service
quarkus.http.auth.proactive=true

# Permitir acceso público a OpenAPI y Swagger UI (Quarkus)
quarkus.http.auth.permission.openapi.paths=/q/openapi*,/q/swagger-ui*
quarkus.http.auth.permission.openapi.policy=permit

# Permiso por defecto para proteger el resto de los endpoints
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated

# Permitir acceso público al endpoint de login
quarkus.http.auth.permission.login.paths=/auth/login
quarkus.http.auth.permission.login.policy=permit

# Permitir acceso público al endpoint de creación de usuario
quarkus.http.auth.permission.createuser.paths=/users
quarkus.http.auth.permission.createuser.policy=permit

# SmallRye OpenAPI
# quarkus.smallrye-openapi.path=/openapi
# Comentado para que Swagger UI use la ruta por defecto /q/openapi
quarkus.smallrye-openapi.enable=true
quarkus.log.console.level=INFO

# Token esperado para el login
auth.client-token=YGMyRIRzM2qa4hYZFxVVqrSQzRWlrZuB
